title: Funny Programming!
description: > # this means to ignore newlines until "baseurl:"
  ED Shin's 삽질을 기록하는 블로그 (About Programming)
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Ed Shin # add your name
author-img: jp-shin.jpg # add your photo
about-author: # add description
about-blog: Shin's 개발 블로그
social-facebook: jp.shin.kor
social-github: ed-shin # add your Github handle
social-email: jp.shin.kor@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
